# Generated by Django 5.2 on 2025-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('£', 'GBP'), ('₹', 'INR')], default='$', max_length=5),
        ),
    ]
