# Generated by Django 5.2 on 2025-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('£', 'GBP'), ('$', 'USD'), ('€', 'EUR'), ('NT$', 'TWD'), ('¥', 'CNY'), ('₹', 'INR')], default='$', max_length=5),
        ),
    ]
