# Generated by Django 5.2 on 2025-04-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
