# Generated by Django 5.2 on 2025-04-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_expense_total_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total_budget',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
